import Link from "next/link";
import { notFound } from "next/navigation";
import { getMonthlySummary } from "@/lib/db/summaries";
import Card from "@/components/ui/Card";
import Badge from "@/components/ui/Badge";
import { ENTRY_TYPES } from "@/lib/utils/constants";
import type { MonthlySummaryData } from "@/types/summary";
import type { EntryTypeKey } from "@/lib/utils/constants";

const MONTH_NAMES = [
  "", "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

interface PageProps {
  params: Promise<{ year: string; month: string }>;
}

export default async function SummaryDetailPage({ params }: PageProps) {
  const { year: yearStr, month: monthStr } = await params;
  const year = parseInt(yearStr);
  const month = parseInt(monthStr);

  const summary = await getMonthlySummary(year, month);
  if (!summary) {
    notFound();
  }

  const data = summary.summary as unknown as MonthlySummaryData;

  return (
    <div>
      <Link
        href="/summaries"
        className="text-sm text-[#c47a2b] hover:text-[#9a5f1e] mb-2 inline-block"
      >
        &larr; Back to summaries
      </Link>

      <h1 className="text-2xl font-bold text-[#1a1714] mb-6">
        {MONTH_NAMES[month]} {year}
      </h1>

      <Card className="mb-4">
        <p className="text-[#2d2822] leading-relaxed">{data.textSummary}</p>
        <p className="text-xs text-[#9a9187] mt-3">
          Generated by: {data.generatedBy === "ai" ? "AI" : "Template"}
        </p>
      </Card>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-4">
        <Card padding="sm">
          <p className="text-2xl font-bold text-[#c47a2b]">
            {data.entryCount}
          </p>
          <p className="text-xs text-[#9a9187]">Total entries</p>
        </Card>
        {Object.entries(data.countByType).map(([type, count]) => {
          const typeInfo = ENTRY_TYPES[type as EntryTypeKey];
          return (
            <Card padding="sm" key={type}>
              <p className="text-2xl font-bold text-[#2d2822]">{count}</p>
              <p className="text-xs text-[#9a9187]">
                {typeInfo?.icon} {typeInfo?.label || type}
              </p>
            </Card>
          );
        })}
      </div>

      {data.topRatedEntries.length > 0 && (
        <Card className="mb-4">
          <h2 className="text-sm font-medium text-[#9a9187] mb-3">
            Top rated entries
          </h2>
          <div className="space-y-2">
            {data.topRatedEntries.map((entry) => {
              const typeInfo = ENTRY_TYPES[entry.type as EntryTypeKey];
              return (
                <Link
                  key={entry.id}
                  href={`/entries/${entry.id}`}
                  className="flex items-center justify-between py-2 hover:bg-[#f5efe8] rounded px-2 transition-colors"
                >
                  <div className="flex items-center gap-2">
                    <Badge variant={entry.type.toLowerCase() as "podcast" | "book" | "article" | "personal_writing"}>
                      {typeInfo?.icon} {typeInfo?.label}
                    </Badge>
                    <span className="text-[#1a1714] font-medium">
                      {entry.title}
                    </span>
                  </div>
                  <div className="flex gap-0.5">
                    {Array.from({ length: entry.rating }).map((_, i) => (
                      <span key={i} className="w-2 h-2 rounded-full bg-[#c47a2b]" />
                    ))}
                  </div>
                </Link>
              );
            })}
          </div>
        </Card>
      )}

      {data.mostUsedTags.length > 0 && (
        <Card>
          <h2 className="text-sm font-medium text-[#9a9187] mb-3">
            Top themes
          </h2>
          <div className="flex gap-2 flex-wrap">
            {data.mostUsedTags.map((tag) => (
              <Link key={tag.name} href={`/entries?tag=${tag.name}`}>
                <Badge>
                  {tag.name} ({tag.count})
                </Badge>
              </Link>
            ))}
          </div>
        </Card>
      )}
    </div>
  );
}
